/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib;

/**
 *
 * @author Iris Kamylle
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        returnbooks = new javax.swing.JButton();
        view = new javax.swing.JButton();
        view2 = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        borrowbooks = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/icons8-borrow-book-100.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 90, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/icons8-return-book-100.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 90, 90));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/icons8-open-book-100.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 100, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/icons8-books-100.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 100, 110));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/icons8-admin-75 (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 100));

        returnbooks.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        returnbooks.setText("Return Books");
        getContentPane().add(returnbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 120, 40));

        view.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        view.setText("View Borrow Books");
        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 160, 40));

        view2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        view2.setText("View Available Books");
        getContentPane().add(view2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 160, 40));

        profile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        profile.setText("Profile");
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, 30));

        borrowbooks.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        borrowbooks.setText("Borrow Books");
        getContentPane().add(borrowbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 120, 40));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User Dashboard");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 10, 430, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 460, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Pink Orange Colorful Book Club Presentation (7).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrowbooks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton profile;
    private javax.swing.JButton returnbooks;
    private javax.swing.JButton view;
    private javax.swing.JButton view2;
    // End of variables declaration//GEN-END:variables
}
