/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib;

import javax.swing.JOptionPane;
import lib.book;

/**
 *
 * @author Iris Kamylle
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        age = new javax.swing.JLabel();
        cpass = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        confirm = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        last = new javax.swing.JTextField();
        first = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        age.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        age.setText("Age:");
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        cpass.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cpass.setText("Confirm Password:");
        getContentPane().add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        lname.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lname.setText("Last Name:");
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        pass.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pass.setText("Password:");
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        user.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        user.setText("Username:");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        fname.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        fname.setText("First Name:");
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        email.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        email.setText("Email:");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 50, 20));
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 140, 40));
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 210, 40));
        getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 140, 40));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 140, 40));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 140, 40));
        getContentPane().add(last, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 140, 40));
        getContentPane().add(first, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 140, 40));

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Pink Orange Colorful Book Club Presentation (10).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 797, 452));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (first.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out First Name");
        }
        else if (last.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out Last Name");
        }
        else if (edad.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out Age");
        }
        else if (mail.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out Email");
        }
        else if (username.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out Username");
        }
        else if (password.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out Password");
        }
        else if (confirm.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out Confirm Password");
        }
        else{

            JOptionPane.showMessageDialog(null, "Registered Successfully");    
        
            book DashboardFrame = new book();
            DashboardFrame.setVisible(true);
            DashboardFrame.pack();
            DashboardFrame.setLocationRelativeTo(null);
            this.dispose();
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JTextField confirm;
    private javax.swing.JLabel cpass;
    private javax.swing.JTextField edad;
    private javax.swing.JLabel email;
    private javax.swing.JTextField first;
    private javax.swing.JLabel fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField last;
    private javax.swing.JLabel lname;
    private javax.swing.JTextField mail;
    private javax.swing.JLabel pass;
    private javax.swing.JTextField password;
    private javax.swing.JLabel user;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
